### ISSUE TITLE
TestableResponseFactory does not create successful responses

### ISSUE THREAD

**Issue by obtuse-whoosh** [elastic/elastic-transport-net#64]
**Expected**

```cs
var response = TestableResponseFactory.CreateSuccessfulResponse<DeleteByQueryResponse>(new(), 200);
Assert.True(response.IsSuccess()); // should be true!
Assert.True(response.IsValidResponse); // should be true!
```

**Actual**
`IsSuccess()` returns false.
`IsValidResponse` also returns false

**Versions**
Elastic.Clients.Elasticsearch v8.0.5
Elastic.Transport v0.4.6

**Comment by obtuse-whoosh** [comment]
Maybe I'm doing this wron, but theres no documentation on this stuff (or unit tests to use as examples).

**Comment by obtuse-whoosh** [comment]
It should also be noted that trying to get the `DebugInformation` from a testable response object throws a null ref exception.

**Comment by stevejgordon** [comment]
@obtuse-whoosh We didn't document this yet as it's an initial feature we wanted to spend a little more time on, including testing. We broke this with some other work for API compatibility headers a while back. Thanks for your PR. At a glance, it looks to fix that issue as planned.
