### ISSUE TITLE
Null reference exception in HttpTransportClient.Request ContentType check with ElasticCloud 8.8.1

### ISSUE THREAD

**Issue by HenkHui** [elastic/elastic-transport-net#76]
There seems to be an issue in the HttpTransportClient In combination with ElasticCloud 8.8.1.

I am using the Elastic.Serilog.Sinks (version 8.6.0) Nuget package which internally uses the Elastic.Transport 0.4.5 assembly to talk to Elasticsearch. In my code I am using the following code to connect Serilog to ElasticCloud:

`.WriteTo.ElasticCloud(<cloudId>, <apiKey>, 
		configureOptions: opts =>
		{
			opts.DataStream = new DataStreamName("logs", "xxx, "xxx");
			opts.BootstrapMethod = BootstrapMethod.Failure;
		});`

NB: I want the code to bootstrap Elasticsearch if needed -> BootstrapMethod.Failure.

However, the code doesn't work because of a Nullreference exception occuring when checking whether the index template already exists. I managed to investigate the issue and it seems that when the HEAD request is executed to check whether the index exists ElasticCloud version 8.8.1 does not return a ContentType header. I have confirmed this using Postman. Could be this is because of the 404 statuscode indicating that the index template does not exist.

The code in Components/TransportClient/HttpTransportClient.cs cannot deal with a response without a ContentType header.
Line 89:

`mimeType = responseMessage.Content.Headers.ContentType.ToString();`

A null check should be added or "ContentType?." should be used.

Any ideas on how to work around this (temporarily)? Can I somehow create a copy of this class, fix the issue and register it to be used in my code?

---- Update ----

I can confirm that this is indeed an issue while bootstrapping ElasticSearch using the HttpTransportClient. I managed to use a "fixed" HttpTransportClient and changed

`mimeType = responseMessage.Content.Headers.ContentType.ToString();`

to

`mimeType = responseMessage.Content.Headers.ContentType?.ToString();`

And now the bootstrapping (checking index template exists and if not creating it) works.

After bootstrapping was done, I could go back to the "old" HttpTransportClient and changed BootstrapMethod to BootstrapMethod.None, to make sure the faulty code was not hit anymore.

-----

Kind regards,
Henk

**Comment by HenkHui** [comment]
@stevejgordon Could you please have a look at this issue? Without a fix we are unable to use the Elastic.Serilog.Sinks library with ElasticCloud. I would be happy to create a PR, however not sure if this is worth the "hassle" for just one "?".

Thanks!
Henk

**Comment by Mpdreamz** [comment]
Thanks for raising this @HenkHui! Opened https://github.com/elastic/elastic-transport-net/pull/78 to address this.
